modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved"

[[mods]]
modId = "@env{mod.id}"
version = "@env{mod.version}"
displayName = "Valleys and Vistas"
# updateJSONURL="https://change.me.example.invalid/updates.json"
# displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
# logoFile="examplemod.png"
credits = "Valleys and Vistas by Autumn, ShadewEnder and YakiYuki"
authors = "Autumn, ShadewEnder and YakiYuki"
description = '''
Valleys and Vistas aims at improving the environment of Minecraft with small new features
'''

[[dependencies."@env{mod.id}"]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."@env{mod.id}"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
